version: 2
project_name: stackcord

before:
  hooks:
    - sh -c "cd cli && go mod verify && go test ./..."

builds:
  - id: stackcord
    dir: ./cli
    main: ./cmd/stackcord
    binary: stackcord
    env:
      - CGO_ENABLED=0
    goos: [darwin, windows]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -buildid= -X main.version={{.Version}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: stackcord
    ids: [stackcord]
    formats: [binary]
    name_template: "stackcord_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  replace_existing_draft: false

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
